apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-worker
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-worker
  template:
    metadata:
      labels:
        app: order-worker
    spec:
      containers:
        - name: order-worker
          image: order-worker:v1
          imagePullPolicy: Never
          args: ["-A", "order_worker", "worker", "--loglevel=info", "-Q", "order_processing", "--concurrency=4"]
          command: ["celery"]
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: MYSQL_PORT
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: MYSQL_DB
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: RABBITMQ_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: MYSQL_PASSWORD
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: RABBITMQ_PASSWORD
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command:
                - celery
                - -A
                - order_worker
                - inspect
                - ping
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command:
                - celery
                - -A
                - order_worker
                - inspect
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
