apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: ecommerce
type: Opaque
stringData:
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "rootpass"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
